### ISSUE TITLE
copy/paste pixel indexing bug in Compare16()

### ISSUE THREAD

**Issue by dmwilk** [aubonbeurre/goicmp#1]
Hi Alex!

```
var c = pic1.RGBA64At(x+i, y+i)
```

should be

```
var c = pic1.RGBA64At(x+i, y+j)
```

while in here probably worth factoring out the accumulation loop so you don't have to fix the bug in two places :-)

**Comment by aubonbeurre** [comment]
Thanks for the feedback! I posted a later version, no way really to test it as this module predates go modules. I hope it will be clearer/less buggy
